import type { Product } from './products';

const products: Product[] = [
  {
    id: 'product-22211665081.2415',
    name: 'TEST NUMERO UNOOOOOOO',
    description:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    short_description:
      '• 50% cotton, 50% polyester\n• Collar, cuffs, and waistband are ribbed with spandex\n• Pill-resistant air jet yarn\n• Tubular body',
    categories: ['hoodie', 'graphic'],
    variants: [
      {
        id: 'variant-1234512sdddsdsd34123',
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
        ],
        custom_fields: [
          {
            name: 'color',
            value: 'black',
          },
          {
            name: 'size',
            value: 's',
          },
        ],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: true,
        sku: "asdasdasd",
      },
      {
        id: 'variant-1234512341ccccc23',
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
        ],
        custom_fields: [
          {
            name: 'color',
            value: 'black',
          },
          {
            name: 'size',
            value: 'l',
          },
        ],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: false,
        sku: "asdasdasd",
      },
      {
        id: 'variant-123451234123<<d',
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
        ],
        custom_fields: [
          {
            name: 'color',
            value: 'black',
          },
          {
            name: 'size',
            value: 'xl',
          },
        ],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: false,
        sku: "asdasdasd",
      },
      {
        id: 'variant-123451234123<<d',
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
        ],
        custom_fields: [
          {
            name: 'color',
            value: 'green',
          },
          {
            name: 'size',
            value: 's',
          },
        ],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: false,
        sku: "asdasdasd",
      },
      {
        id: 'variant-1234512zzzzzzz34123',
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
        ],
        custom_fields: [
          {
            name: 'color',
            value: 'pink',
          },
          {
            name: 'size',
            value: 's',
          },
        ],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: false,
        sku: "asdasdasd",
      },
      {
        id: 'variant-123451rwrwrwrw234123',
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
        ],
        custom_fields: [
          {
            name: 'color',
            value: 'pink',
          },
          {
            name: 'size',
            value: 'large',
          },
        ],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: false,
        sku: "asdasdasd",
      },
      {
        id: 'variant-12345123gasga4123',
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2652-600x800.jpg',
        ],
        custom_fields: [
          {
            name: 'color',
            value: 'pink',
          },
          {
            name: 'size',
            value: 'xl',
          },
        ],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: false,
        sku: "asdasdasd",
      },
    ],
    width: 0,
    height: 0,
    depth: 0,
    weight: 0,
    base_price: 42.0,
    tax_amount: 24,
    net_price: 31.49,
    promotion: null,
  },
  {
    id: 'product-93544342407.43356',
    name: 'WHO AM I HOODIE',
    description:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    short_description:
      '50% cotton, 50% polyester\nCollar, cuffs, and waistband are ribbed with spandex\nPill-resistant air jet yarn\nTubular body',

    categories: ['hoodie', 'graphic'],
    variants: [
      {
        id: `variant-${Date.now() * Math.random()}`,
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
        ],
        custom_fields: [],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: true,
        sku: "asdasdasd",
      },
      {
        id: `variant-${Date.now() * Math.random()}`,
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
        ],
        custom_fields: [],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: false,
        sku: "asdasdasd",
      },
      {
        id: `variant-${Date.now() * Math.random()}`,
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2401-600x800.jpg',
        ],
        custom_fields: [],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: false,
        sku: "asdasdasd",
      },
    ],
    width: 0,
    height: 0,
    depth: 0,
    weight: 0,
    base_price: 42.0,
    promotion: null,
    tax_amount: 24,
    net_price: 31.49,
  },
  {
    id: 'product-188278388714.30685',
    name: 'WHO AM I HOODIE',
    description:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    short_description:
      '• 50% cotton, 50% polyester\n• Collar, cuffs, and waistband are ribbed with spandex\n• Pill-resistant air jet yarn\n• Tubular body',

    categories: ['hoodie', 'graphic'],
    variants: [
      {
        id: `variant-${Date.now() * Math.random()}`,
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
        ],
        custom_fields: [],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: true,
        sku: "asdasdasd",
      },
      {
        id: `variant-${Date.now() * Math.random()}`,
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
        ],
        custom_fields: [],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: false,
        sku: "asdasdasd",
      },
      {
        id: `variant-${Date.now() * Math.random()}`,
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2641-600x800.jpg',
        ],
        custom_fields: [],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: false,
        sku: "asdasdasd",
      },
    ],
    width: 0,
    height: 0,
    depth: 0,
    weight: 0,
    base_price: 42.0,
    promotion: null,
    tax_amount: 24,
    net_price: 31.49,
  },
  {
    id: 'product-243902897414.3342',
    name: 'WHO AM I HOODIE',
    description:
      '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    short_description:
      '• 50% cotton, 50% polyester\n• Collar, cuffs, and waistband are ribbed with spandex\n• Pill-resistant air jet yarn\n• Tubular body',

    categories: ['hoodie', 'graphic'],
    variants: [
      {
        id: `variant-${Date.now() * Math.random()}`,
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
        ],
        custom_fields: [],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: true,
        sku: "asdasdasd",
      },
      {
        id: `variant-${Date.now() * Math.random()}`,
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
        ],
        custom_fields: [],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: false,
        sku: "asdasdasd",
      },
      {
        id: `variant-${Date.now() * Math.random()}`,
        media: [
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
          'https://higherplane-images.s3.eu-west-1.amazonaws.com/images/FD_Webshop_DSC_2512-600x800.jpg',
        ],
        custom_fields: [],
        list_price: null,
        discount_amount: null,
        tax_amount: null,
        purchasing_disabled: false,
        primary: false,
        sku: "asdasdasd",
      },
    ],
    width: 0,
    height: 0,
    depth: 0,
    weight: 0,
    base_price: 42.0,
    promotion: null,
    tax_amount: 24,
    net_price: 31.49,
  },
];

export default products;